### ISSUE TITLE
It does not generate the JSON file

### ISSUE THREAD

**Issue by monkeylijin** [ribice/glice#35]
Why is it that when I use "glice -i go.mod -fmt=json -o sss.json" it does not generate the JSON file? What could be the issue?

**Comment by monkeylijin** [comment]
glice -i go.mod -fmt json -o sss.json  "Is it using this command, or is it reporting an error?"

**Comment by ribice** [comment]
I just tested it and it works as expected:

```
glice git:(master) glice -fmt="json"
[{"name":"github.com/fatih/color","url":"https://github.com/fatih/color","host":"github.com","author":"fatih","project":"color","license":"MIT"},{"name":"github.com/google/go-github","url":"https://github.com/google/go-github","host":"github.com","author":"google","project":"go-github","license":"bsd-3-clause"},{"name":"github.com/keighl/metabolize","url":"https://github.com/keighl/metabolize","host":"github.com","author":"keighl","project":"metabolize","license":"Other"},{"name":"github.com/olekukonko/tablewriter","url":"https://github.com/olekukonko/tablewriter","host":"github.com","author":"olekukonko","project":"tablewriter","license":"MIT"},{"name":"golang.org/x/mod","url":"https://go.googlesource.com/mod","host":"go.googlesource.com","author":"mod","license":""},{"name":"golang.org/x/oauth2","url":"https://go.googlesource.com/oauth2","host":"go.googlesource.com","author":"oauth2","license":""}]
```

**Comment by monkeylijin** [comment]
Thanks for your reply, I see that the golang.org type of dependent license information in your json has no license information. Is this tool temporarily not supported?

**Comment by monkeylijin** [comment]
<img width="1366" alt="image" src="https://github.com/ribice/glice/assets/26971206/3e79cd95-c111-4c39-865c-a19c3c347e2d">
<img width="1188" alt="image" src="https://github.com/ribice/glice/assets/26971206/e111aa3f-5849-45c1-b9f9-1b21f35732b8">
Why doesn't it work?

**Comment by ribice** [comment]
I assumed the issue you have is with JSON output.

And no, glice currently only gets licenses for repositories hosted on github.com

Feel free to create a PR with support for golang.org
