### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by alamin-mahamud** [ribice/glice#9]
$ glice
panic: runtime error: index out of range

goroutine 1 [running]:
main.main()
        $GOPATH/pkg/mod/github.com/ribice/glice@v0.0.0-20181011133736-685f13fa9b12/main.go:58 +0x5cd

**Comment by ribice** [comment]
It is related to Go modules usage.

At that line I get the project directory after `src` (which is the structure of Go when using GOPATH), which doesn't exist when using Go Modules.

**Comment by alamin-mahamud** [comment]
Yes you are correct. when I did `glice` in project without go modules there I saw it working correctly.

What should I do if I want to use it with go modules.

**Comment by ribice** [comment]
Create a PR or wait for me to rewrite `glice`.
